services:
  postgres:
    container_name: "postgres"
    image: postgres:13-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - filkompedia

  redis:
    container_name: "redis"
    image: redis:alpine
    command: redis-server
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASS}
    volumes:
      - ./redis_data:/data
    networks:
      - whale_ai

  filkompedia_be:
    container_name: "filkompedia-be"
    build:
      context: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - filkompedia
    depends_on:
      - postgres
    restart: on-failure

  filkompedia_fe:
    container_name: "filkompedia-fe"
    build:
      context: ../filkompedia-fe
    ports:
      - "5173:5173"
    networks:
      - filkompedia
    depends_on:
      - filkompedia_be
    restart: on-failure
    environment:
      - VITE_API_URL=${VITE_API_URL}

networks:
  filkompedia:
    name: filkompedia
    driver: bridge