global:
  scrape_interval: "5s"
  evaluation_interval: "5s"

alerting: 

rule_files:

# make sure ports are the same with .env
scrape_configs:
  - job_name: filkompedia
    static_configs:
      - targets:
          - filkompedia_be:3001
